//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tieuluan_ban_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DatHang
    {
        public int So_Don_Hang { get; set; }
        public int Ma_Giay { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual Don_Dat_Hang Don_Dat_Hang { get; set; }
        public virtual Giay Giay { get; set; }
    }
}
