//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tieuluan_ban_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khach_Hang()
        {
            this.Don_Dat_Hang = new HashSet<Don_Dat_Hang>();
            this.Gio_Hang = new HashSet<Gio_Hang>();
        }
    
        public int Ma_Khach_Hang { get; set; }
        public string Ten_Khach_Hang { get; set; }
        public string DiaChi_Khach_Hang { get; set; }
        public string DienThoai_khach_Hang { get; set; }
        public string TenDN_Khach_Hang { get; set; }
        public string MatKhau_Khach_Hang { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
        public string ResetPasswordCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Dat_Hang> Don_Dat_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gio_Hang> Gio_Hang { get; set; }
    }
}
