//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tieuluan_ban_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quan_Tri
    {
        public int Ma_Admin { get; set; }
        public string Ten_Admin { get; set; }
        public string DiaChi_Admin { get; set; }
        public Nullable<int> DienThoai_Admin { get; set; }
        public string TenDN_Admin { get; set; }
        public string MatKhau_Admin { get; set; }
        public Nullable<System.DateTime> NgaySinh_Admin { get; set; }
        public string GioiTinh_Admin { get; set; }
        public string Email_Admin { get; set; }
    }
}
